name:                oefen2
version:             0.1.0.0
github:              "githubuser/oefen2"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/oefen2#readme>

dependencies:
  - name: base
    version: ">= 4.7 && < 5"
 
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  oefening1:
    main: Main.hs
    source-dirs: app/oefening1
    ghc-options:
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wmissing-export-lists
      - -Wmissing-home-modules
      - -Wpartial-fields
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - oefen2
      - base >= 4.7 && < 5

  oefening2:
    main: Main.hs
    source-dirs: app/oefening2
    ghc-options:
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wmissing-export-lists
      - -Wmissing-home-modules
      - -Wpartial-fields
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - oefen2
      - base >= 4.7 && < 5

  oefening3:
    main: Main.hs
    source-dirs: app/oefening3
    ghc-options:
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wmissing-export-lists
      - -Wmissing-home-modules
      - -Wpartial-fields
      - -Wredundant-constraints
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - oefen2
      - base >= 4.7 && < 5


tests:
  oefen2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oefen2
